# Uncomment the next line to define a global platform for your project
platform :ios, '10.1'

source 'https://github.com/CocoaPods/Specs.git'
target 'GAILocationScreen' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GAILocationScreen
  pod 'GoogleMaps'
  pod 'GooglePlaces'


end
